spring:
  datasource:
    username: root
    password: 19971001
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.134.151:3306/gulimall_oms
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #数据格式化，该包可以控制后端返回的时间
  redis:
    host: 192.168.134.151
    port: 6379
# *的意思是扫描的位置包含我的引入的jar包，如果不写就是只扫描自己的
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 23000
#mapper-locations: classpath*:/mapper/**/*.xml